version: 2.1

jobs:
  deploy_to_kubernetes:
    docker:
      - image: alpine/k8s:1.26.13  # Docker image with kubectl tools
    steps:
      - checkout  # Checkout the repo files

      # Step 1: Set up AWS Credentials
      - run:
          name: Set Up AWS Credentials
          command: |
            echo "Setting up AWS credentials"
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

      # Step 2: Verify AWS Credentials (Optional debugging)
      - run:
          name: Verify AWS Credentials
          command: |
            echo "Verifying AWS credentials..."
            aws sts get-caller-identity --query "Arn" --output text
            aws ec2 describe-regions --query "Regions[*].RegionName" --output text

      # Step 3: Decode and Verify Kubeconfig File
      - run:
          name: Decode and Verify Kubeconfig
          command: |
            # Decode the Kubeconfig and save it to a file
            echo $KUBECONFIG_DATA | base64 -d > kubeconfig
            export KUBECONFIG=kubeconfig

            # Display the Kubeconfig content (for debugging)
            echo "Kubeconfig file content:"
            cat $KUBECONFIG

            # List available contexts
            kubectl config get-contexts

            # Set and verify the correct context
            kubectl config use-context arn:aws:eks:$AWS_DEFAULT_REGION:$AWS_ACCOUNT_ID:cluster/$EKS_CLUSTER_NAME

            # Verify the current context
            kubectl config current-context

      # Step 4: Deploy to Kubernetes (EKS)
      - run:
          name: Deploy to Kubernetes (EKS)
          command: |
            kubectl apply -f mongo-secrets.yaml
            kubectl apply -f mongo.yaml
            kubectl apply -f mongo-configMap.yaml
            kubectl apply -f mongo-express.yaml
            kubectl apply -f my-app.yaml

workflows:
  version: 2
  deploy:
    jobs:
      - deploy_to_kubernetes
