version: 2.1

jobs:
  deploy_to_kubernetes:
    docker:
      - image: alpine/k8s:1.26.13  # Use a Docker image with kubectl tools
    steps:
      - checkout  # Checkout the repo files

      # Step 1: Set up AWS Credentials
      - run:
          name: Set Up AWS Credentials
          command: |
            echo "Setting up AWS credentials"
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION

      # Step 2: Verify AWS Credentials
      - run:
          name: Verify AWS Credentials
          command:
            - echo "Verifying AWS credentials..."
            - aws sts get-caller-identity

      # Step 3: Set Up Kubernetes Context for EKS
      - run:
          name: Set Up Kubernetes Context for EKS
          command: |
            aws eks update-kubeconfig --region us-east-1 --name demo-clusture

            # Verify the available contexts
            echo "Available contexts in kubeconfig:"
            kubectl config get-contexts
            kubectl get pods

      # Step 4: Deploy to Kubernetes (EKS)
      - run:
          name: Deploy to Kubernetes (EKS)
          command: |
            kubectl run testpod --image=nginx
workflows:
  version: 2
  deploy:
    jobs:
      - deploy_to_kubernetes
